name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - segovoni
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: command-line
    attributes:
      label: sqlcmdcli command line
      description: What is the command line you used?
      placeholder: Command line without user credentials!
      value: "altercolumn -servername:BEER -databasename:AdventureWorks2017 -username:XXX -password:XXX -schemaname:Person -tablename:Person -columnname:FirstName -datatype:nvarchar(100) -verbose"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.0.127 (Default)
        - 1.0.0.126
        - 1.0.0.112
    validations:
      required: true
  - type: dropdown
    id: sql-server-version
    attributes:
      label: What SQL Server version are you seeing the problem on?
      multiple: true
      options:
        - SQL Server 2022
        - SQL Server 2019
        - SQL Server 2017
        - SQL Server 2016
        - SQL Server 2014
        - SQL Server 2012
        - Azure SQL Database
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
